* Gobi Manchurian

** Ingredients
- 250 grams cauliflower florets (gobi cleaned)
- Oil for deep frying as needed

*To Make Batter*
- ½ cup all-purpose flour (maida, prefer organic or at least unbleached)
- ¼ cup cornstarch (white corn flour or yellow corn flour)
- ½ to 1 teaspoon red chilli powder or paste (less spicy variety) (optional)
- ¼ teaspoon black pepper crushed or ground
- ¼ teaspoon salt (adjust to taste)
- ½ cup water (more if needed)

*To Make Gobi Manchurian Sauce*
- 1½ tablespoons oil (for sauce)
- 1 tablespoon garlic fine chopped
- ½ tablespoon ginger fine chopped
- 1 green chili chopped (optional)
- ⅓ cup onions or spring onions fine chopped
- ¼ cup bell pepper (capsicum chopped fine) (optional)
- 1 tablespoon soya sauce (organic or naturally brewed)(or tamari)
- 2 to 3 tablespoon Red Chilli sauce (or 2 tsps hot sauce, adjust to taste)
- 1 to 2 tablespoon tomato ketchup (optional, use if using hot sauce)
- ½ teaspoon Red chili powder (optional) (less spicy variety)
- ½ tablespoon rice vinegar (I used apple cider vinegar)
- 1 teaspoon sugar (adjust to taste)
- salt as needed
- 3 to 4 tablespoons water
- ½ to ¾ teaspoon black pepper crushed or ground
- ⅛ teaspoon salt (adjust to taste)
- 2 tablespoons spring onion greens chopped for garnish

*** Instructions
*Preparation*
- Clean 250 grams of gobi and cut the florets to medium size.
- Add them to 3 cups of hot water and rest for 5 minutes.
- Later drain the gobi completely to a colander or spread on a clean cloth until no moisture remains on the gobi.
- You can do this ahead and set aside. Any moisture in the gobi will cook it to soft and not crisp.
- Heat up the oil for deep frying on a medium heat.
- Meanwhile make the batter by adding cornstarch, all-purpose flour, red chilli powder, black pepper and salt to a mixing bowl.
- Mix and add water little by little as needed and make a free flowing lump free batter. The consistency has to be medium and not too thick or very runny. Adjust salt as needed by tasting the batter. (check video)
- Then add the gobi florets to the batter in batches, coat them well.

*Fry Cauliflower*
- When the oil turns hot enough, check by dropping a small amount of batter to the hot oil. The batter has to rise without browning. This is the correct temperature.
- Pick up each cauliflower floret with a spoon or fingers & gently drop them one by one to the hot oil. The flame has to be medium initially and should be increased slightly as more gobi is added. Reduce the flame to medium and fry until the florets turn golden and crisp. Keep stirring in between for even frying.
- Drain them to a kitchen tissue or a steel colander. Repeat the same steps of adding the rest of the cauliflower florets to the batter, coating them well and then frying them in hot oil until crisp.
- For extra crisp gobi manchurian, you can also refry the once fried gobi again in oil. I usually do not do it as frying them once is good enough to get very good crisp manchurian with this recipe.

*How to Make Gobi Manchurian*
- Mix together red chili powder with little water to a paste and keep aside. This step is optional and is used mainly for the red color.
- Heat 1½ tablespoons oil in a wide pan.
- When the oil turns hot, add garlic, ginger and green chilies. Saute for a minute or two.
- Then add spring onions & capsicum. Saute them on a high flame for 2 mins.
- Add soya sauce, red chili sauce, tomato ketchup, red chili paste, sugar and vinegar. (for gravy version refer the notes section below).
- Mix and add water. Mix and cook stirring and add pepper.
- Cook on a medium heat until the sauce thickens.
- Turn off the stove and check the taste.
- The sauce has to be slightly sour, sweet & hot. If needed you can adjust the salt & add more sauces as well.
- Allow the sauce to cool for 1 to 2 mins.
- Add the fried cauliflower and stir gently to coat the gobi well with the manchurian sauce.
- Garnish gobi manchurian with spring onion greens.
- Serve immediately as a appetizer or as a side with noodles or fried rice.
